[project]
name = "compscifromscratch"
version = "0.1.0"
description = "Small projects to learn computer science concepts using Python."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
